openapi: 3.0.1
info:
  title: MockAPI
  description: API Definition of MockAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/mock
paths:
  /:
    post:
      responses:
        default:
          description: Default response
