openapi: 3.0.1
info:
  title: UserRegistrationAPI
  description: API Definition of UserRegistrationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/registeruserapi
paths:
  /:
    post:
      responses:
        default:
          description: Default response
