openapi: 3.0.1
info:
  title: SalesForceAccountServiceAPI
  description: API Definition of SalesForceAccountServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/salesforceaccountapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
