openapi: 3.0.1
info:
  title: UserInfoRestAPI
  description: API Definition of UserInfoRestAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/userInfo
paths:
  /users:
    get:
      responses:
        default:
          description: Default response
